GRANT USAGE ON SCHEMA todoapp TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA todoapp TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA todoapp TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA todoapp TO "apps";